//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.09 at 06:11:41 PM MSD 
//


package org.riverock.update.webmill.v580.convert_template.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element ref="{http://webmill.riverock.org/xsd/riverock-template-page-elements.xsd}dynamic"/>
 *         &lt;element ref="{http://webmill.riverock.org/xsd/riverock-template-page-elements.xsd}portlet"/>
 *         &lt;element ref="{http://webmill.riverock.org/xsd/riverock-template-page-elements.xsd}xslt"/>
 *         &lt;element ref="{http://webmill.riverock.org/xsd/riverock-template-page-elements.xsd}include"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dynamicOrPortletOrXslt"
})
@XmlRootElement(name = "Template", namespace = "")
public class Template {

    @XmlElements({
        @XmlElement(name = "dynamic", type = Dynamic.class),
        @XmlElement(name = "include", type = Include.class),
        @XmlElement(name = "xslt", type = Xslt.class),
        @XmlElement(name = "portlet", type = Portlet.class)
    })
    protected List<Object> dynamicOrPortletOrXslt;

    /**
     * Gets the value of the dynamicOrPortletOrXslt property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dynamicOrPortletOrXslt property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDynamicOrPortletOrXslt().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Dynamic }
     * {@link Include }
     * {@link Xslt }
     * {@link Portlet }
     * 
     * 
     */
    public List<Object> getDynamicOrPortletOrXslt() {
        if (dynamicOrPortletOrXslt == null) {
            dynamicOrPortletOrXslt = new ArrayList<Object>();
        }
        return this.dynamicOrPortletOrXslt;
    }

}
