//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.04 at 04:42:58 PM MSD 
//


package org.riverock.update.webmill.v580.convert_template.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{}script"/>
 *           &lt;element ref="{}style"/>
 *           &lt;element ref="{}meta"/>
 *           &lt;element ref="{}link"/>
 *           &lt;element ref="{}object"/>
 *           &lt;element ref="{http://webmill.riverock.org/xsd/riverock-template-page-elements.xsd}custom"/>
 *           &lt;element ref="{http://webmill.riverock.org/xsd/riverock-template-page-elements.xsd}portlet"/>
 *         &lt;/choice>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element ref="{}title"/>
 *             &lt;choice maxOccurs="unbounded" minOccurs="0">
 *               &lt;element ref="{}script"/>
 *               &lt;element ref="{}style"/>
 *               &lt;element ref="{}meta"/>
 *               &lt;element ref="{}link"/>
 *               &lt;element ref="{}object"/>
 *             &lt;/choice>
 *             &lt;sequence minOccurs="0">
 *               &lt;element ref="{}base"/>
 *               &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                 &lt;element ref="{}script"/>
 *                 &lt;element ref="{}style"/>
 *                 &lt;element ref="{}meta"/>
 *                 &lt;element ref="{}link"/>
 *                 &lt;element ref="{}object"/>
 *               &lt;/choice>
 *             &lt;/sequence>
 *           &lt;/sequence>
 *           &lt;sequence>
 *             &lt;element ref="{}base"/>
 *             &lt;choice maxOccurs="unbounded" minOccurs="0">
 *               &lt;element ref="{}script"/>
 *               &lt;element ref="{}style"/>
 *               &lt;element ref="{}meta"/>
 *               &lt;element ref="{}link"/>
 *               &lt;element ref="{}object"/>
 *             &lt;/choice>
 *             &lt;sequence>
 *               &lt;element ref="{}title"/>
 *               &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                 &lt;element ref="{}script"/>
 *                 &lt;element ref="{}style"/>
 *                 &lt;element ref="{}meta"/>
 *                 &lt;element ref="{}link"/>
 *                 &lt;element ref="{}object"/>
 *               &lt;/choice>
 *             &lt;/sequence>
 *           &lt;/sequence>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="dir">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="ltr"/>
 *             &lt;enumeration value="rtl"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="lang" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="profile" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute ref="{http://www.w3.org/XML/1998/namespace}lang"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "head")
public class Head {

    @XmlElementRefs({
        @XmlElementRef(name = "script", type = Script.class),
        @XmlElementRef(name = "object", type = org.riverock.update.webmill.v580.convert_template.schema.Object.class),
        @XmlElementRef(name = "base", type = Base.class),
        @XmlElementRef(name = "portlet", namespace = "http://webmill.riverock.org/xsd/riverock-template-page-elements.xsd", type = Portlet.class),
        @XmlElementRef(name = "style", type = Style.class),
        @XmlElementRef(name = "title", type = Title.class),
        @XmlElementRef(name = "custom", namespace = "http://webmill.riverock.org/xsd/riverock-template-page-elements.xsd", type = Custom.class),
        @XmlElementRef(name = "link", type = Link.class),
        @XmlElementRef(name = "meta", type = Meta.class)
    })
    protected List<java.lang.Object> content;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String dir;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    @XmlAttribute(name = "lang")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String oldLang;
    @XmlAttribute
    protected String profile;
    @XmlAttribute(namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String lang;

    /**
     * Gets the rest of the content model. 
     * 
     * <p>
     * You are getting this "catch-all" property because of the following reason: 
     * The field name "Base" is used by two different parts of a schema. See: 
     * line 108 of file:/C:/sandbox/riverock/trunk/riverock-update/src/main/xsd/riverock-template.xsd
     * line 97 of file:/C:/sandbox/riverock/trunk/riverock-update/src/main/xsd/riverock-template.xsd
     * <p>
     * To get rid of this property, apply a property customization to one 
     * of both of the following declarations to change their names: 
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link org.riverock.update.webmill.v580.convert_template.schema.Object }
     * {@link Script }
     * {@link Base }
     * {@link Style }
     * {@link Portlet }
     * {@link Title }
     * {@link Link }
     * {@link Custom }
     * {@link Meta }
     * 
     * 
     */
    public List<java.lang.Object> getContent() {
        if (content == null) {
            content = new ArrayList<java.lang.Object>();
        }
        return this.content;
    }

    /**
     * Gets the value of the dir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDir() {
        return dir;
    }

    /**
     * Sets the value of the dir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDir(String value) {
        this.dir = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the oldLang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOldLang() {
        return oldLang;
    }

    /**
     * Sets the value of the oldLang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOldLang(String value) {
        this.oldLang = value;
    }

    /**
     * Gets the value of the profile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProfile() {
        return profile;
    }

    /**
     * Sets the value of the profile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProfile(String value) {
        this.profile = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

}
