CREATE TABLE WM_FORUM_MESSAGE
  (
  M_ICONID NUMBER (5, 0) DEFAULT 0 NOT NULL,
  M_T_ID NUMBER (7, 0) NOT NULL,
  M_ID NUMBER (7, 0) NOT NULL,
  M_CONTENT VARCHAR2 (4000),
  M_U_ID NUMBER (7, 0) NOT NULL,
  M_TIME DATE DEFAULT sysdate NOT NULL,
  COUNT_EDITED NUMBER (5, 0) DEFAULT 0 NOT NULL,
  LAST_EDITED DATE DEFAULT sysdate NOT NULL
 )
     TABLESPACE MILLENNIUM
 PARALLEL
/