CREATE TABLE WM_FORUM_CATEGORY
  (
  FORUM_CATEGORY_ID NUMBER (7, 0) NOT NULL,
  FORUM_ID NUMBER (7, 0) NOT NULL,
  FORUM_CATEGORY_NAME VARCHAR2 (150) NOT NULL,
  IS_USE_LOCALE NUMBER (1, 0) DEFAULT 0 NOT NULL
 )
     TABLESPACE MILLENNIUM
 PARALLEL
/