CREATE TABLE WM_FORUM
  (
  FORUM_ID NUMBER (7) NOT NULL,
  S_USE_LOCALE NUMBER (1, 0) DEFAULT 0 NOT NULL,
  SITE_ID NUMBER (7) NOT NULL,
  FORUM_NAME VARCHAR2 (200) NOT NULL,
  IS_DELETED NUMBER (1, 0) DEFAULT 0 NOT NULL
 )
     TABLESPACE MILLENNIUM
 PARALLEL
/