CREATE TABLE WM_FORUM_TOPIC
  (
  T_ORDER NUMBER (5, 0) DEFAULT 0 NOT NULL,
  T_LOCKED NUMBER (1, 0) DEFAULT 0 NOT NULL,
  T_ICONID NUMBER (3, 0) DEFAULT 0 NOT NULL,
  T_F_ID NUMBER (7, 0) NOT NULL,
  T_ID NUMBER (7, 0) NOT NULL,
  T_NAME VARCHAR2 (150) NOT NULL,
  T_U_ID NUMBER (7, 0) NOT NULL,
  T_REPLIES NUMBER (7, 0) DEFAULT 0 NOT NULL,
  T_VIEWS NUMBER (7, 0) DEFAULT 0 NOT NULL,
  T_U_ID2 NUMBER (7, 0) NOT NULL,
  T_LASTTIME DATE DEFAULT sysdate NOT NULL
 )
     TABLESPACE MILLENNIUM
 PARALLEL
/