//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.4-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.11.25 at 01:15:53 AM MSK 
//


package org.riverock.portlet.news.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NewsGroupType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NewsGroupType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NewsGroupName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NewsItem" type="{}NewsItemType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="NewsGroupCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="maxNews" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="newsGroupId" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="orderValue" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NewsGroupType", propOrder = {
    "newsGroupName",
    "newsItem",
    "newsGroupCode"
})
public class NewsGroupType {

    @XmlElement(name = "NewsGroupName", required = true)
    protected String newsGroupName;
    @XmlElement(name = "NewsItem")
    protected List<NewsItemType> newsItem;
    @XmlElement(name = "NewsGroupCode")
    protected String newsGroupCode;
    @XmlAttribute
    protected Long maxNews;
    @XmlAttribute
    protected Long newsGroupId;
    @XmlAttribute
    protected Integer orderValue;

    /**
     * Gets the value of the newsGroupName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewsGroupName() {
        return newsGroupName;
    }

    /**
     * Sets the value of the newsGroupName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewsGroupName(String value) {
        this.newsGroupName = value;
    }

    /**
     * Gets the value of the newsItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the newsItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNewsItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NewsItemType }
     * 
     * 
     */
    public List<NewsItemType> getNewsItem() {
        if (newsItem == null) {
            newsItem = new ArrayList<NewsItemType>();
        }
        return this.newsItem;
    }

    /**
     * Gets the value of the newsGroupCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewsGroupCode() {
        return newsGroupCode;
    }

    /**
     * Sets the value of the newsGroupCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewsGroupCode(String value) {
        this.newsGroupCode = value;
    }

    /**
     * Gets the value of the maxNews property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMaxNews() {
        return maxNews;
    }

    /**
     * Sets the value of the maxNews property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMaxNews(Long value) {
        this.maxNews = value;
    }

    /**
     * Gets the value of the newsGroupId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getNewsGroupId() {
        return newsGroupId;
    }

    /**
     * Sets the value of the newsGroupId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setNewsGroupId(Long value) {
        this.newsGroupId = value;
    }

    /**
     * Gets the value of the orderValue property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getOrderValue() {
        return orderValue;
    }

    /**
     * Sets the value of the orderValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setOrderValue(Integer value) {
        this.orderValue = value;
    }

}
