ADD INDEX `WPC_ID_SITE_LANG_CATALOG_URL` ( `ID_SITE_CTX_LANG_CATALOG` , `CTX_PAGE_URL` ) 
/

ADD INDEX `WM_WEBCLIP_ID_SITE_IDX` ( `ID_SITE` ) 
/

ALTER TABLE `WM_PORTLET_WEBCLIP` CHANGE `ID_SITE` `ID_SITE` DECIMAL( 10, 0 ) NOT NULL 
/

ALTER TABLE `WM_PORTLET_WEBCLIP` CHANGE `DATE_POST` `DATE_POST` TIMESTAMP NULL 
/

ADD INDEX `WPX_ID_SITE_LANGUAGE_IDX` ( `ID_SITE_SUPPORT_LANGUAGE` ) 
/

ADD INDEX `WPT_ID_SITE_LANGUAGE_IDX` ( `ID_SITE_SUPPORT_LANGUAGE` ) 
/

ADD INDEX `WPSL_ID_SITE_IDX` ( `ID_SITE` ) 
/



