--ALTER TABLE SITE_XSLT drop CONSTRAINT ID_SITE_SUPPORT_LANG_SX_FK
--/

ALTER TABLE SITE_XSLT ADD CONSTRAINT ID_SITE_SUPPORT_LANG_SX_FK
  FOREIGN KEY (
ID_SITE_SUPPORT_LANGUAGE
)
 REFERENCES SITE_SUPPORT_LANGUAGE
 (
ID_SITE_SUPPORT_LANGUAGE
) 

/
