//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.4-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.11.25 at 01:13:48 AM MSK 
//


package org.riverock.portlet.article.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ArticleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ArticleType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ArticleDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ArticleTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ArticleName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ArticleText" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArticleType", propOrder = {
    "articleDate",
    "articleTime",
    "articleName",
    "articleText"
})
public class ArticleType {

    @XmlElement(name = "ArticleDate", required = true)
    protected String articleDate;
    @XmlElement(name = "ArticleTime", required = true)
    protected String articleTime;
    @XmlElement(name = "ArticleName", required = true)
    protected String articleName;
    @XmlElement(name = "ArticleText", required = true)
    protected String articleText;

    /**
     * Gets the value of the articleDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArticleDate() {
        return articleDate;
    }

    /**
     * Sets the value of the articleDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArticleDate(String value) {
        this.articleDate = value;
    }

    /**
     * Gets the value of the articleTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArticleTime() {
        return articleTime;
    }

    /**
     * Sets the value of the articleTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArticleTime(String value) {
        this.articleTime = value;
    }

    /**
     * Gets the value of the articleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArticleName() {
        return articleName;
    }

    /**
     * Sets the value of the articleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArticleName(String value) {
        this.articleName = value;
    }

    /**
     * Gets the value of the articleText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArticleText() {
        return articleText;
    }

    /**
     * Sets the value of the articleText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArticleText(String value) {
        this.articleText = value;
    }

}
