create table WM_PORTLET_WEBCLIP
(
ID_WEBCLIP DECIMAL NOT NULL ,
ID_SITE DECIMAL,
DATE_POST TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
WEBCLIP_DATA VARCHAR(1),
 PRIMARY KEY (
ID_WEBCLIP
)
)
/

create table WM_PORTLET_WEBCLIP_DATA
(
ID_WEBCLIP_DATA DECIMAL NOT NULL ,
ID_WEBCLIP DECIMAL,
WEBCLIP_DATA TEXT,
 PRIMARY KEY (
ID_WEBCLIP_DATA
)
)