CREATE TABLE wm_portlet_search (
  ID_SITE NUMBER(10,0) NOT NULL,
  SEARCH_DATE DATE NOT NULL default SYSDATE,
  WORD varchar2(50) default NULL
) 
/

ALTER TABLE WM_PORTAL_LIST_SITE 
 MODIFY (
  DEF_COUNTRY DEFAULT NULL NULL

 )
/