CREATE TABLE wm_portlet_search (
  ID_SITE NUMBER(10,0) NOT NULL,
  SEARCH_DATE DATE NOT NULL default SYSDATE,
  WORD varchar2(50) default NULL
) 
/

ALTER TABLE WM_PORTAL_LIST_SITE 
 MODIFY (
  DEF_COUNTRY DEFAULT NULL NULL

 )
/

CREATE SEQUENCE SEQ_WM_PORTLET_WEBCLIP
 START WITH  1
 INCREMENT BY  1
 MINVALUE  1
 MAXVALUE  9999999999
 NOCACHE 
 NOCYCLE 
/

CREATE SEQUENCE SEQ_WM_PORTLET_WEBCLIP_DATA
 START WITH  1
 INCREMENT BY  1
 MINVALUE  1
 MAXVALUE  9999999999
 NOCACHE 
 NOCYCLE 
/