ALTER TABLE MILLENNIUM.SITE_CONTENT_CSS ADD CONSTRAINT ID_SITE_SUPPORT_LANG_SCC_FK
  FOREIGN KEY (
ID_SITE_SUPPORT_LANGUAGE
)
 REFERENCES MILLENNIUM.SITE_SUPPORT_LANGUAGE
 (
ID_SITE_SUPPORT_LANGUAGE
) 
/
