CREATE TABLE WM_FORUM_USER
  (
  U_ID NUMBER (7, 0) NOT NULL,
  U_AVATAR_ID NUMBER (5, 0) DEFAULT 0 NOT NULL,
  U_SIGN VARCHAR2 (150),
  U_POST NUMBER (7, 0) DEFAULT o NOT NULL,
  U_LASTTIME DATE DEFAULT sysdate NOT NULL,
  U_LASTIP VARCHAR2 (25) NOT NULL
 )
     TABLESPACE MILLENNIUM
 PARALLEL
/