rename table AUTH_ACCESS_GROUP to WM_AUTH_ACCESS_GROUP
/

rename table AUTH_ARM to WM_AUTH_APPLICATION
/

rename table AUTH_RELATE_ACCGROUP  to WM_AUTH_RELATE_ACCGROUP
/

rename table AUTH_RELATE_RIGHT_ARM  to WM_AUTH_RELATE_RIGHT_ARM
/

rename table AUTH_USER  to WM_AUTH_USER
/




