//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.4-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.07.24 at 07:30:25 PM MSD 
//


package org.riverock.webmill.template.schema.elements;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.riverock.webmill.template.schema.elements package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Portlet_QNAME = new QName("http://webmill.riverock.org/xsd/riverock-template-page-elements.xsd", "portlet");
    private final static QName _Custom_QNAME = new QName("http://webmill.riverock.org/xsd/riverock-template-page-elements.xsd", "custom");
    private final static QName _Dynamic_QNAME = new QName("http://webmill.riverock.org/xsd/riverock-template-page-elements.xsd", "dynamic");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.riverock.webmill.template.schema.elements
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PortletType }
     * 
     */
    public PortletType createPortletType() {
        return new PortletType();
    }

    /**
     * Create an instance of {@link DynamicType }
     * 
     */
    public DynamicType createDynamicType() {
        return new DynamicType();
    }

    /**
     * Create an instance of {@link ParameterType }
     * 
     */
    public ParameterType createParameterType() {
        return new ParameterType();
    }

    /**
     * Create an instance of {@link CustomType }
     * 
     */
    public CustomType createCustomType() {
        return new CustomType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PortletType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webmill.riverock.org/xsd/riverock-template-page-elements.xsd", name = "portlet")
    public JAXBElement<PortletType> createPortlet(PortletType value) {
        return new JAXBElement<PortletType>(_Portlet_QNAME, PortletType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustomType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webmill.riverock.org/xsd/riverock-template-page-elements.xsd", name = "custom")
    public JAXBElement<CustomType> createCustom(CustomType value) {
        return new JAXBElement<CustomType>(_Custom_QNAME, CustomType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DynamicType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://webmill.riverock.org/xsd/riverock-template-page-elements.xsd", name = "dynamic")
    public JAXBElement<DynamicType> createDynamic(DynamicType value) {
        return new JAXBElement<DynamicType>(_Dynamic_QNAME, DynamicType.class, null, value);
    }

}
