//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.4-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.11.26 at 03:57:27 PM MSK 
//


package org.riverock.commerce.schema.shop;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CurrentBasketType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CurrentBasketType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ItemInBasket" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="CurrentBasketUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CurrentBasketName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CurrentBasketType", propOrder = {
    "itemInBasket",
    "currentBasketUrl",
    "currentBasketName"
})
public class CurrentBasketType {

    @XmlElement(name = "ItemInBasket")
    protected int itemInBasket;
    @XmlElement(name = "CurrentBasketUrl", required = true)
    protected String currentBasketUrl;
    @XmlElement(name = "CurrentBasketName", required = true)
    protected String currentBasketName;

    /**
     * Gets the value of the itemInBasket property.
     * 
     */
    public int getItemInBasket() {
        return itemInBasket;
    }

    /**
     * Sets the value of the itemInBasket property.
     * 
     */
    public void setItemInBasket(int value) {
        this.itemInBasket = value;
    }

    /**
     * Gets the value of the currentBasketUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrentBasketUrl() {
        return currentBasketUrl;
    }

    /**
     * Sets the value of the currentBasketUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrentBasketUrl(String value) {
        this.currentBasketUrl = value;
    }

    /**
     * Gets the value of the currentBasketName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrentBasketName() {
        return currentBasketName;
    }

    /**
     * Sets the value of the currentBasketName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrentBasketName(String value) {
        this.currentBasketName = value;
    }

}
