//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.11.24 at 10:53:49 AM MSK 
//


package org.riverock.generic.annotation.schema.db;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DbImportedPKColumn complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DbImportedPKColumn">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="UpdateRule" type="{http://generic.riverock.org/xsd/riverock-database-structure.xsd}DbKeyActionRule" minOccurs="0"/>
 *         &lt;element name="DeleteRule" type="{http://generic.riverock.org/xsd/riverock-database-structure.xsd}DbKeyActionRule" minOccurs="0"/>
 *         &lt;element name="Deferrability" type="{http://generic.riverock.org/xsd/riverock-database-structure.xsd}DbKeyActionRule" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="fkColumnName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="fkName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="fkSchemaName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="fkTableName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="keySeq" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="pkColumnName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="pkName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="pkSchemaName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="pkTableName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DbImportedPKColumn", propOrder = {
    "updateRule",
    "deleteRule",
    "deferrability"
})
public class DbImportedPKColumn {

    @XmlElement(name = "UpdateRule")
    protected DbKeyActionRule updateRule;
    @XmlElement(name = "DeleteRule")
    protected DbKeyActionRule deleteRule;
    @XmlElement(name = "Deferrability")
    protected DbKeyActionRule deferrability;
    @XmlAttribute
    protected String fkColumnName;
    @XmlAttribute
    protected String fkName;
    @XmlAttribute
    protected String fkSchemaName;
    @XmlAttribute
    protected String fkTableName;
    @XmlAttribute
    protected Integer keySeq;
    @XmlAttribute
    protected String pkColumnName;
    @XmlAttribute
    protected String pkName;
    @XmlAttribute
    protected String pkSchemaName;
    @XmlAttribute
    protected String pkTableName;

    /**
     * Gets the value of the updateRule property.
     * 
     * @return
     *     possible object is
     *     {@link DbKeyActionRule }
     *     
     */
    public DbKeyActionRule getUpdateRule() {
        return updateRule;
    }

    /**
     * Sets the value of the updateRule property.
     * 
     * @param value
     *     allowed object is
     *     {@link DbKeyActionRule }
     *     
     */
    public void setUpdateRule(DbKeyActionRule value) {
        this.updateRule = value;
    }

    /**
     * Gets the value of the deleteRule property.
     * 
     * @return
     *     possible object is
     *     {@link DbKeyActionRule }
     *     
     */
    public DbKeyActionRule getDeleteRule() {
        return deleteRule;
    }

    /**
     * Sets the value of the deleteRule property.
     * 
     * @param value
     *     allowed object is
     *     {@link DbKeyActionRule }
     *     
     */
    public void setDeleteRule(DbKeyActionRule value) {
        this.deleteRule = value;
    }

    /**
     * Gets the value of the deferrability property.
     * 
     * @return
     *     possible object is
     *     {@link DbKeyActionRule }
     *     
     */
    public DbKeyActionRule getDeferrability() {
        return deferrability;
    }

    /**
     * Sets the value of the deferrability property.
     * 
     * @param value
     *     allowed object is
     *     {@link DbKeyActionRule }
     *     
     */
    public void setDeferrability(DbKeyActionRule value) {
        this.deferrability = value;
    }

    /**
     * Gets the value of the fkColumnName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFkColumnName() {
        return fkColumnName;
    }

    /**
     * Sets the value of the fkColumnName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFkColumnName(String value) {
        this.fkColumnName = value;
    }

    /**
     * Gets the value of the fkName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFkName() {
        return fkName;
    }

    /**
     * Sets the value of the fkName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFkName(String value) {
        this.fkName = value;
    }

    /**
     * Gets the value of the fkSchemaName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFkSchemaName() {
        return fkSchemaName;
    }

    /**
     * Sets the value of the fkSchemaName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFkSchemaName(String value) {
        this.fkSchemaName = value;
    }

    /**
     * Gets the value of the fkTableName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFkTableName() {
        return fkTableName;
    }

    /**
     * Sets the value of the fkTableName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFkTableName(String value) {
        this.fkTableName = value;
    }

    /**
     * Gets the value of the keySeq property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getKeySeq() {
        return keySeq;
    }

    /**
     * Sets the value of the keySeq property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setKeySeq(Integer value) {
        this.keySeq = value;
    }

    /**
     * Gets the value of the pkColumnName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPkColumnName() {
        return pkColumnName;
    }

    /**
     * Sets the value of the pkColumnName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPkColumnName(String value) {
        this.pkColumnName = value;
    }

    /**
     * Gets the value of the pkName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPkName() {
        return pkName;
    }

    /**
     * Sets the value of the pkName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPkName(String value) {
        this.pkName = value;
    }

    /**
     * Gets the value of the pkSchemaName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPkSchemaName() {
        return pkSchemaName;
    }

    /**
     * Sets the value of the pkSchemaName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPkSchemaName(String value) {
        this.pkSchemaName = value;
    }

    /**
     * Gets the value of the pkTableName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPkTableName() {
        return pkTableName;
    }

    /**
     * Sets the value of the pkTableName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPkTableName(String value) {
        this.pkTableName = value;
    }

}
