/*
 * org.riverock.generic - Database connectivity classes, part of Webmill portal
 * For more information about Webmill portal, please visit project site
 * http://webmill.askmore.info
 *
 * Copyright (C) 2000-2006, Riverock Software, All Rights Reserved.
 *
 * Riverock - The Open-source Java Development Community
 * http://www.riverock.org
 *
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.11.23 at 09:47:05 PM MSK 
//


package org.riverock.generic.annotation.schema.config;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GenericConfigType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GenericConfigType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GenericTempDir" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="GenericDebugDir" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Property" type="{}PropertyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DTS" type="{}DateTimeSavingType" minOccurs="0"/>
 *         &lt;element name="MailHost" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CustomDirs" type="{}CustomDirsType" minOccurs="0"/>
 *         &lt;element name="SecurityKeyStorage" type="{}SecurityKeyStorageType" minOccurs="0"/>
 *         &lt;element name="DefaultConnectionName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DatabaseConnection" type="{}DatabaseConnectionType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="isDebugDirInit" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="isTempDirInit" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GenericConfigType", propOrder = {
    "genericTempDir",
    "genericDebugDir",
    "property",
    "dts",
    "mailHost",
    "customDirs",
    "securityKeyStorage",
    "defaultConnectionName",
    "databaseConnection"
})
public class GenericConfigType {

    @XmlElement(name = "GenericTempDir", defaultValue = "\\\\temp")
    protected String genericTempDir;
    @XmlElement(name = "GenericDebugDir")
    protected String genericDebugDir;
    @XmlElement(name = "Property")
    protected List<PropertyType> property;
    @XmlElement(name = "DTS")
    protected DateTimeSavingType dts;
    @XmlElement(name = "MailHost")
    protected String mailHost;
    @XmlElement(name = "CustomDirs")
    protected CustomDirsType customDirs;
    @XmlElement(name = "SecurityKeyStorage")
    protected SecurityKeyStorageType securityKeyStorage;
    @XmlElement(name = "DefaultConnectionName", required = true, defaultValue = "ORACLE")
    protected String defaultConnectionName;
    @XmlElement(name = "DatabaseConnection", required = true)
    protected List<DatabaseConnectionType> databaseConnection;
    @XmlAttribute
    protected Boolean isDebugDirInit;
    @XmlAttribute
    protected Boolean isTempDirInit;

    /**
     * Gets the value of the genericTempDir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGenericTempDir() {
        return genericTempDir;
    }

    /**
     * Sets the value of the genericTempDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGenericTempDir(String value) {
        this.genericTempDir = value;
    }

    /**
     * Gets the value of the genericDebugDir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGenericDebugDir() {
        return genericDebugDir;
    }

    /**
     * Sets the value of the genericDebugDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGenericDebugDir(String value) {
        this.genericDebugDir = value;
    }

    /**
     * Gets the value of the property property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the property property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PropertyType }
     * 
     * 
     */
    public List<PropertyType> getProperty() {
        if (property == null) {
            property = new ArrayList<PropertyType>();
        }
        return this.property;
    }

    /**
     * Gets the value of the dts property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeSavingType }
     *     
     */
    public DateTimeSavingType getDTS() {
        return dts;
    }

    /**
     * Sets the value of the dts property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeSavingType }
     *     
     */
    public void setDTS(DateTimeSavingType value) {
        this.dts = value;
    }

    /**
     * Gets the value of the mailHost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMailHost() {
        return mailHost;
    }

    /**
     * Sets the value of the mailHost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMailHost(String value) {
        this.mailHost = value;
    }

    /**
     * Gets the value of the customDirs property.
     * 
     * @return
     *     possible object is
     *     {@link CustomDirsType }
     *     
     */
    public CustomDirsType getCustomDirs() {
        return customDirs;
    }

    /**
     * Sets the value of the customDirs property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomDirsType }
     *     
     */
    public void setCustomDirs(CustomDirsType value) {
        this.customDirs = value;
    }

    /**
     * Gets the value of the securityKeyStorage property.
     * 
     * @return
     *     possible object is
     *     {@link SecurityKeyStorageType }
     *     
     */
    public SecurityKeyStorageType getSecurityKeyStorage() {
        return securityKeyStorage;
    }

    /**
     * Sets the value of the securityKeyStorage property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecurityKeyStorageType }
     *     
     */
    public void setSecurityKeyStorage(SecurityKeyStorageType value) {
        this.securityKeyStorage = value;
    }

    /**
     * Gets the value of the defaultConnectionName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultConnectionName() {
        return defaultConnectionName;
    }

    /**
     * Sets the value of the defaultConnectionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultConnectionName(String value) {
        this.defaultConnectionName = value;
    }

    /**
     * Gets the value of the databaseConnection property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the databaseConnection property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDatabaseConnection().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DatabaseConnectionType }
     * 
     * 
     */
    public List<DatabaseConnectionType> getDatabaseConnection() {
        if (databaseConnection == null) {
            databaseConnection = new ArrayList<DatabaseConnectionType>();
        }
        return this.databaseConnection;
    }

    /**
     * Gets the value of the isDebugDirInit property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIsDebugDirInit() {
        if (isDebugDirInit == null) {
            return false;
        } else {
            return isDebugDirInit;
        }
    }

    /**
     * Sets the value of the isDebugDirInit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsDebugDirInit(Boolean value) {
        this.isDebugDirInit = value;
    }

    /**
     * Gets the value of the isTempDirInit property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIsTempDirInit() {
        if (isTempDirInit == null) {
            return false;
        } else {
            return isTempDirInit;
        }
    }

    /**
     * Sets the value of the isTempDirInit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsTempDirInit(Boolean value) {
        this.isTempDirInit = value;
    }

}
