//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.09 at 06:11:41 PM MSD 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://webmill.riverock.org/xsd/riverock-template-page-elements.xsd", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.riverock.update.webmill.v580.convert_template.schema;
